# Generated by Django 6.0 on 2026-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registraion', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('AIML', 'AIML'), ('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('MEC', 'MEC'), ('CIVL', 'CIVL')], max_length=10),
        ),
    ]
