# Generated by Django 6.0 on 2026-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registraion', '0004_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
