# Generated by Django 6.0 on 2026-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registraion', '0005_alter_student_created_at_alter_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile'),
        ),
    ]
