# Generated by Django 6.0 on 2026-02-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registraion', '0006_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
