# Generated by Django 6.0 on 2026-02-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registraion', '0008_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='student_profile/video'),
        ),
    ]
